/**
 * Research Sources Database
 * 181 verified research sources for Swiss AI Labor Market Analysis
 * Generated: 2026-01-25
 */

export interface ResearchSource {
  id: string;
  title: string;
  institution: string;
  year: number;
  abstract: string;
  url: string;
  topics: string[];
}

// =============================================================================
// MASTER LIST OF 181 RESEARCH SOURCES
// =============================================================================

export const RESEARCH_SOURCES: ResearchSource[] = [
  // ===========================================================================
  // 1. SCHWEIZER BEHÖRDEN (Government) - 15 sources
  // ===========================================================================
  {
    id: 'research-bfs-arbeitsmarkt-2024',
    title: 'Arbeitsmarktindikatoren Schweiz',
    institution: 'Bundesamt für Statistik (BFS)',
    year: 2024,
    abstract: 'Offizielle Schweizer Arbeitsmarktstatistiken. Umfasst Erwerbstätigkeit, Arbeitslosigkeit, Löhne, Arbeitsbedingungen und Branchenentwicklung.',
    url: 'https://www.bfs.admin.ch/bfs/de/home/statistiken/arbeit-erwerb.html',
    topics: ['arbeitsmarkt', 'statistik', 'beschäftigung', 'löhne'],
  },
  {
    id: 'research-bfs-bildung-2024',
    title: 'Bildungsstatistik Schweiz',
    institution: 'Bundesamt für Statistik (BFS)',
    year: 2024,
    abstract: 'Statistiken zu Bildung, Ausbildung und Weiterbildung in der Schweiz. Umfasst Hochschulbildung, Berufsbildung und lebenslanges Lernen.',
    url: 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft.html',
    topics: ['bildung', 'ausbildung', 'weiterbildung', 'hochschule'],
  },
  {
    id: 'research-bfs-ict-2024',
    title: 'Informationsgesellschaft - Indikatoren',
    institution: 'Bundesamt für Statistik (BFS)',
    year: 2024,
    abstract: 'Statistiken zur digitalen Transformation der Schweiz. ICT-Nutzung in Unternehmen und Haushalten, E-Commerce, Cybersecurity.',
    url: 'https://www.bfs.admin.ch/bfs/de/home/statistiken/kultur-medien-informationsgesellschaft-sport/informationsgesellschaft.html',
    topics: ['digitalisierung', 'ict', 'internet', 'e-commerce'],
  },
  {
    id: 'research-bfs-innovation-2024',
    title: 'Forschung und Entwicklung Schweiz',
    institution: 'Bundesamt für Statistik (BFS)',
    year: 2024,
    abstract: 'Statistiken zu F&E-Ausgaben, Patenten und Innovationsaktivitäten in der Schweiz. Vergleich mit anderen Ländern.',
    url: 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bildung-wissenschaft/technologie.html',
    topics: ['forschung', 'innovation', 'patente', 'technologie'],
  },
  {
    id: 'research-seco-konjunktur-2024',
    title: 'Konjunkturprognosen',
    institution: 'SECO',
    year: 2024,
    abstract: 'Offizielle Konjunkturprognosen der Schweizer Regierung. Vierteljährliche Analysen zu BIP-Entwicklung, Arbeitsmarkt und Wirtschaftsaussichten.',
    url: 'https://www.seco.admin.ch/seco/de/home/wirtschaftslage---wirtschaftspolitik/Wirtschaftslage/konjunkturprognosen.html',
    topics: ['konjunktur', 'prognose', 'wirtschaft', 'arbeitsmarkt'],
  },
  {
    id: 'research-seco-arbeitslosenstatistik-2024',
    title: 'Arbeitslosenstatistik',
    institution: 'SECO',
    year: 2024,
    abstract: 'Monatliche Arbeitslosenzahlen und Analyse der Arbeitsmarktentwicklung in der Schweiz nach Regionen und Branchen.',
    url: 'https://www.seco.admin.ch/seco/de/home/Arbeit/Arbeitslosenversicherung/arbeitslosenzahlen.html',
    topics: ['arbeitslosigkeit', 'arbeitsmarkt', 'regionen', 'branchen'],
  },
  {
    id: 'research-seco-fachkraefte-2024',
    title: 'Fachkräfteinitiative',
    institution: 'SECO',
    year: 2024,
    abstract: 'Massnahmen und Analysen zur Bekämpfung des Fachkräftemangels in der Schweiz. Fokus auf MINT-Berufe und Digitalisierung.',
    url: 'https://www.seco.admin.ch/seco/de/home/Arbeit/Fachkraefteinitiative.html',
    topics: ['fachkräftemangel', 'mint', 'weiterbildung', 'arbeitsmarkt'],
  },
  {
    id: 'research-sbfi-berufsbildung-2024',
    title: 'Berufsbildung in der Schweiz',
    institution: 'SBFI',
    year: 2024,
    abstract: 'Staatssekretariat für Bildung, Forschung und Innovation - Fakten und Zahlen zur Berufsbildung.',
    url: 'https://www.sbfi.admin.ch/sbfi/de/home/bildung/berufsbildungssteuerung-und--politik/berufsbildung-in-der-schweiz.html',
    topics: ['berufsbildung', 'lehre', 'ausbildung', 'duale bildung'],
  },
  {
    id: 'research-sbfi-forschung-2024',
    title: 'Forschung und Innovation in der Schweiz',
    institution: 'SBFI',
    year: 2024,
    abstract: 'Bericht über Forschung und Innovation in der Schweiz, Förderprogramme und internationale Zusammenarbeit.',
    url: 'https://www.sbfi.admin.ch/sbfi/de/home/forschung-und-innovation.html',
    topics: ['forschung', 'innovation', 'förderprogramme', 'wissenschaft'],
  },
  {
    id: 'research-innosuisse-report-2024',
    title: 'Innosuisse Jahresbericht',
    institution: 'Innosuisse',
    year: 2024,
    abstract: 'Schweizerische Agentur für Innovationsförderung - Jahresbericht über geförderte Projekte und Innovationslandschaft.',
    url: 'https://www.innosuisse.ch/inno/de/home/ueber-uns/zahlen-und-fakten.html',
    topics: ['innovation', 'förderung', 'startups', 'technologietransfer'],
  },
  {
    id: 'research-snf-forschung-2024',
    title: 'Forschungsförderung Schweiz',
    institution: 'Schweizerischer Nationalfonds (SNF)',
    year: 2024,
    abstract: 'Übersicht über Forschungsförderung und wissenschaftliche Projekte in der Schweiz, inkl. AI-Forschung.',
    url: 'https://www.snf.ch/de',
    topics: ['grundlagenforschung', 'wissenschaft', 'förderung', 'ai research'],
  },
  {
    id: 'research-digitale-verwaltung-2024',
    title: 'Digitale Verwaltung Schweiz',
    institution: 'Digitale Verwaltung Schweiz',
    year: 2024,
    abstract: 'E-Government Strategie und Umsetzung in der Schweiz. Digitale Transformation der öffentlichen Verwaltung.',
    url: 'https://www.digitale-verwaltung-schweiz.ch/',
    topics: ['e-government', 'digitalisierung', 'verwaltung', 'öffentlicher sektor'],
  },
  {
    id: 'research-bakom-digital-2024',
    title: 'Strategie Digitale Schweiz',
    institution: 'BAKOM',
    year: 2024,
    abstract: 'Bundesamt für Kommunikation - Strategie für die digitale Transformation der Schweiz.',
    url: 'https://www.bakom.admin.ch/bakom/de/home/digital-und-internet/strategie-digitale-schweiz.html',
    topics: ['digitale strategie', 'infrastruktur', 'breitband', 'digitalpolitik'],
  },
  {
    id: 'research-edoeb-datenschutz-2024',
    title: 'Datenschutz und AI',
    institution: 'EDÖB',
    year: 2024,
    abstract: 'Eidgenössischer Datenschutz- und Öffentlichkeitsbeauftragter - Leitlinien zu AI und Datenschutz.',
    url: 'https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/arbeit_wirtschaft/kuenstliche-intelligenz.html',
    topics: ['datenschutz', 'ai', 'privacy', 'regulierung'],
  },
  {
    id: 'research-snb-stability-2024',
    title: 'Financial Stability Report',
    institution: 'SNB',
    year: 2024,
    abstract: 'Swiss National Bank assessment of financial sector stability covering banks, insurance, fintech, and AI adoption in financial services.',
    url: 'https://www.snb.ch/en/publications/financial-stability-report',
    topics: ['financial stability', 'fintech', 'digitalization', 'banking'],
  },

  // ===========================================================================
  // 2. INTERNATIONAL ORGANIZATIONS - 25 sources
  // ===========================================================================
  {
    id: 'research-oecd-employment-2024',
    title: 'OECD Employment Outlook 2024',
    institution: 'OECD',
    year: 2024,
    abstract: 'Annual flagship publication on labor markets in OECD countries including Switzerland. Analyzes AI impact on jobs, skills requirements, and policy responses.',
    url: 'https://www.oecd.org/employment/outlook/',
    topics: ['employment', 'ai impact', 'skills', 'policy'],
  },
  {
    id: 'research-oecd-skills-2024',
    title: 'OECD Skills Outlook',
    institution: 'OECD',
    year: 2024,
    abstract: 'Analysis of skills development and lifelong learning policies. Focus on digital skills and AI-era competencies.',
    url: 'https://www.oecd.org/education/oecd-skills-outlook/',
    topics: ['skills', 'education', 'lifelong learning', 'digital competencies'],
  },
  {
    id: 'research-oecd-ai-policy-2024',
    title: 'OECD AI Policy Observatory',
    institution: 'OECD',
    year: 2024,
    abstract: 'Comprehensive database of AI policies and initiatives across OECD countries. Policy recommendations and best practices.',
    url: 'https://oecd.ai/',
    topics: ['ai policy', 'regulation', 'governance', 'best practices'],
  },
  {
    id: 'research-oecd-education-2024',
    title: 'Education at a Glance',
    institution: 'OECD',
    year: 2024,
    abstract: 'International comparison of education systems. Switzerland rankings in educational attainment and investment.',
    url: 'https://www.oecd.org/education/education-at-a-glance/',
    topics: ['education', 'comparison', 'statistics', 'investment'],
  },
  {
    id: 'research-oecd-digital-economy-2024',
    title: 'OECD Digital Economy Outlook',
    institution: 'OECD',
    year: 2024,
    abstract: 'Analysis of digital transformation trends, AI adoption, and economic impacts across OECD countries.',
    url: 'https://www.oecd.org/digital/oecd-digital-economy-outlook/',
    topics: ['digital economy', 'ai adoption', 'transformation', 'productivity'],
  },
  {
    id: 'research-oecd-future-work-2024',
    title: 'The Future of Work',
    institution: 'OECD',
    year: 2024,
    abstract: 'OECD research on how digitalization and AI are reshaping labor markets, skills demand, and social protection.',
    url: 'https://www.oecd.org/future-of-work/',
    topics: ['future of work', 'digitalization', 'social protection', 'labor market'],
  },
  {
    id: 'research-wef-future-jobs-2023',
    title: 'Future of Jobs Report 2023',
    institution: 'World Economic Forum',
    year: 2023,
    abstract: 'Global report on labor market transformation through 2027. Projects 23% of jobs to change in next 5 years, with 69M new jobs created and 83M displaced.',
    url: 'https://www.weforum.org/publications/the-future-of-jobs-report-2023/',
    topics: ['future of work', 'skills', 'job creation', 'displacement'],
  },
  {
    id: 'research-wef-global-risks-2024',
    title: 'Global Risks Report 2024',
    institution: 'World Economic Forum',
    year: 2024,
    abstract: 'Annual assessment of global risks including AI-related disruptions, labor market instability, and technological governance challenges.',
    url: 'https://www.weforum.org/publications/global-risks-report-2024/',
    topics: ['global risks', 'ai risks', 'technology', 'governance'],
  },
  {
    id: 'research-wef-competitiveness-2024',
    title: 'Global Competitiveness Report',
    institution: 'World Economic Forum',
    year: 2024,
    abstract: 'Country rankings on competitiveness factors including innovation, technology adoption, and human capital.',
    url: 'https://www.weforum.org/publications/the-global-competitiveness-report/',
    topics: ['competitiveness', 'innovation', 'technology', 'human capital'],
  },
  {
    id: 'research-wef-davos-ai-2024',
    title: 'AI Governance Alliance',
    institution: 'World Economic Forum',
    year: 2024,
    abstract: 'WEF initiative on responsible AI development and deployment. Guidelines for AI governance in business.',
    url: 'https://www.weforum.org/communities/ai-governance-alliance/',
    topics: ['ai governance', 'responsible ai', 'ethics', 'business'],
  },
  {
    id: 'research-imf-weo-2024',
    title: 'World Economic Outlook',
    institution: 'IMF',
    year: 2024,
    abstract: 'Global economic analysis examining macroeconomic trends, growth forecasts, and AI impact on productivity and labor markets across advanced economies.',
    url: 'https://www.imf.org/en/Publications/WEO',
    topics: ['global economy', 'productivity', 'ai impact', 'economic growth'],
  },
  {
    id: 'research-imf-ai-labor-2024',
    title: 'AI and the Future of Work',
    institution: 'IMF',
    year: 2024,
    abstract: 'IMF research on how AI will affect employment, wages, and inequality across advanced and emerging economies.',
    url: 'https://www.imf.org/en/Topics/AI',
    topics: ['ai', 'employment', 'wages', 'inequality'],
  },
  {
    id: 'research-imf-switzerland-2024',
    title: 'IMF Country Report: Switzerland',
    institution: 'IMF',
    year: 2024,
    abstract: 'IMF assessment of Swiss economy including labor market, productivity, and digital transformation challenges.',
    url: 'https://www.imf.org/en/Countries/CHE',
    topics: ['switzerland', 'economy', 'assessment', 'policy'],
  },
  {
    id: 'research-worldbank-jobs-2024',
    title: 'World Development Report: Jobs',
    institution: 'World Bank',
    year: 2024,
    abstract: 'Analysis of global labor market trends, technological change, and policy responses for inclusive growth.',
    url: 'https://www.worldbank.org/en/topic/jobsanddevelopment',
    topics: ['jobs', 'development', 'technology', 'policy'],
  },
  {
    id: 'research-worldbank-digital-2024',
    title: 'Digital Development',
    institution: 'World Bank',
    year: 2024,
    abstract: 'World Bank research on digital transformation, connectivity, and technology-driven economic development.',
    url: 'https://www.worldbank.org/en/topic/digitaldevelopment',
    topics: ['digital development', 'connectivity', 'technology', 'growth'],
  },
  {
    id: 'research-ilo-future-work-2024',
    title: 'Future of Work - Global Commission Report',
    institution: 'ILO',
    year: 2024,
    abstract: 'UN agency analysis of global labor market transformation with framework for human-centered approach including social protection and lifelong learning.',
    url: 'https://www.ilo.org/global/topics/future-of-work/lang--en/index.htm',
    topics: ['future of work', 'social protection', 'skills', 'decent work'],
  },
  {
    id: 'research-ilo-ai-work-2024',
    title: 'Generative AI and Jobs',
    institution: 'ILO',
    year: 2024,
    abstract: 'ILO research on generative AI impact on employment, particularly for developing countries and vulnerable workers.',
    url: 'https://www.ilo.org/global/topics/artificial-intelligence/lang--en/index.htm',
    topics: ['generative ai', 'employment', 'workers', 'protection'],
  },
  {
    id: 'research-ilo-skills-2024',
    title: 'Skills and Employability',
    institution: 'ILO',
    year: 2024,
    abstract: 'ILO framework for skills development and employability in the age of automation and AI.',
    url: 'https://www.ilo.org/global/topics/skills-knowledge-and-employability/lang--en/index.htm',
    topics: ['skills', 'employability', 'training', 'lifelong learning'],
  },
  {
    id: 'research-eu-ai-act-2024',
    title: 'EU AI Act',
    institution: 'European Commission',
    year: 2024,
    abstract: 'Comprehensive EU regulation on artificial intelligence. Risk-based framework for AI development and deployment.',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai',
    topics: ['ai regulation', 'eu law', 'risk framework', 'governance'],
  },
  {
    id: 'research-eu-digital-decade-2024',
    title: 'Digital Decade 2030',
    institution: 'European Commission',
    year: 2024,
    abstract: 'EU digital transformation targets for 2030 including skills, infrastructure, business digitalization, and public services.',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/europes-digital-decade',
    topics: ['digital targets', 'infrastructure', 'skills', 'transformation'],
  },
  {
    id: 'research-eu-digital-economy-2024',
    title: 'Digital Economy and Society Index',
    institution: 'European Commission',
    year: 2024,
    abstract: 'Annual monitoring of digital progress across European countries. Comparison of digital competitiveness.',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/desi',
    topics: ['digital index', 'comparison', 'progress', 'competitiveness'],
  },
  {
    id: 'research-unesco-ai-ethics-2024',
    title: 'Recommendation on the Ethics of AI',
    institution: 'UNESCO',
    year: 2024,
    abstract: 'Global standard-setting instrument on AI ethics. Framework for responsible AI development and human rights protection.',
    url: 'https://www.unesco.org/en/artificial-intelligence/recommendation-ethics',
    topics: ['ai ethics', 'human rights', 'global standards', 'responsible ai'],
  },
  {
    id: 'research-un-digital-cooperation-2024',
    title: 'Roadmap for Digital Cooperation',
    institution: 'United Nations',
    year: 2024,
    abstract: 'UN Secretary-General roadmap for inclusive digital future including AI governance and digital skills.',
    url: 'https://www.un.org/en/content/digital-cooperation-roadmap/',
    topics: ['digital cooperation', 'ai governance', 'inclusion', 'skills'],
  },
  {
    id: 'research-unctad-digital-2024',
    title: 'Digital Economy Report',
    institution: 'UNCTAD',
    year: 2024,
    abstract: 'UN report on global digital economy trends, data flows, and AI development disparities.',
    url: 'https://unctad.org/topic/ecommerce-and-digital-economy/digital-economy-report',
    topics: ['digital economy', 'data', 'ai', 'development'],
  },
  {
    id: 'research-bis-fintech-2024',
    title: 'BIS Innovation Hub',
    institution: 'Bank for International Settlements',
    year: 2024,
    abstract: 'Central bank innovation research including AI in financial services, CBDC, and fintech supervision.',
    url: 'https://www.bis.org/about/bisih/about.htm',
    topics: ['fintech', 'ai finance', 'central banks', 'innovation'],
  },

  // ===========================================================================
  // 3. CONSULTING FIRMS - 31 sources
  // ===========================================================================
  {
    id: 'research-mckinsey-genai-2023',
    title: 'The economic potential of generative AI',
    institution: 'McKinsey Global Institute',
    year: 2023,
    abstract: 'Comprehensive analysis of how generative AI could transform productivity across industries. Estimates generative AI could add $2.6-4.4 trillion annually to the global economy.',
    url: 'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai-the-next-productivity-frontier',
    topics: ['generative ai', 'automation', 'productivity', 'labor market'],
  },
  {
    id: 'research-mckinsey-automation-2023',
    title: 'Jobs lost, jobs gained: Workforce transitions',
    institution: 'McKinsey Global Institute',
    year: 2023,
    abstract: 'Analysis of workforce displacement and creation from automation. Scenarios for job transitions through 2030.',
    url: 'https://www.mckinsey.com/featured-insights/future-of-work/jobs-lost-jobs-gained-what-the-future-of-work-will-mean-for-jobs-skills-and-wages',
    topics: ['automation', 'job displacement', 'workforce', 'skills'],
  },
  {
    id: 'research-mckinsey-skills-2024',
    title: 'Skill shift: Automation and the future of the workforce',
    institution: 'McKinsey Global Institute',
    year: 2024,
    abstract: 'Analysis of changing skill requirements. Growing demand for technological, social-emotional, and higher cognitive skills.',
    url: 'https://www.mckinsey.com/featured-insights/future-of-work/skill-shift-automation-and-the-future-of-the-workforce',
    topics: ['skills', 'automation', 'workforce', 'reskilling'],
  },
  {
    id: 'research-mckinsey-state-ai-2024',
    title: 'The state of AI in 2024',
    institution: 'McKinsey & Company',
    year: 2024,
    abstract: 'Annual survey of AI adoption across industries. Trends in gen AI use, organizational challenges, and business value.',
    url: 'https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai',
    topics: ['ai adoption', 'enterprise ai', 'gen ai', 'business value'],
  },
  {
    id: 'research-mckinsey-future-work-2024',
    title: 'The future of work after COVID-19',
    institution: 'McKinsey Global Institute',
    year: 2024,
    abstract: 'Post-pandemic labor market analysis. Acceleration of automation, remote work trends, and occupational shifts.',
    url: 'https://www.mckinsey.com/featured-insights/future-of-work/the-future-of-work-after-covid-19',
    topics: ['future of work', 'remote work', 'automation', 'post-pandemic'],
  },
  {
    id: 'research-bcg-ai-scale-2024',
    title: 'AI at Scale',
    institution: 'Boston Consulting Group',
    year: 2024,
    abstract: 'Research on scaling AI in organizations. Identifies success factors and common pitfalls in enterprise AI adoption.',
    url: 'https://www.bcg.com/publications/2024/ai-at-scale',
    topics: ['ai scaling', 'enterprise ai', 'transformation', 'adoption'],
  },
  {
    id: 'research-bcg-genai-productivity-2024',
    title: 'How Generative AI Boosts Productivity',
    institution: 'Boston Consulting Group',
    year: 2024,
    abstract: 'Study on productivity gains from generative AI tools. Impact on knowledge worker tasks and creative processes.',
    url: 'https://www.bcg.com/publications/2024/how-generative-ai-boosts-productivity',
    topics: ['generative ai', 'productivity', 'knowledge workers', 'automation'],
  },
  {
    id: 'research-bcg-future-work-2024',
    title: 'The Future of Work Is Now',
    institution: 'Boston Consulting Group',
    year: 2024,
    abstract: 'BCG research on workforce transformation, skill development strategies, and organizational adaptation to AI.',
    url: 'https://www.bcg.com/capabilities/people-strategy/future-of-work',
    topics: ['future of work', 'workforce', 'skills', 'organization'],
  },
  {
    id: 'research-deloitte-ai-enterprise-2024',
    title: 'State of AI in the Enterprise',
    institution: 'Deloitte',
    year: 2024,
    abstract: 'Enterprise AI adoption survey examining implementation, scaling challenges, ROI metrics, and workforce transformation strategies.',
    url: 'https://www2.deloitte.com/us/en/pages/consulting/articles/state-of-ai-in-the-enterprise.html',
    topics: ['enterprise ai', 'adoption', 'digital transformation', 'roi'],
  },
  {
    id: 'research-deloitte-tech-trends-2024',
    title: 'Tech Trends 2024',
    institution: 'Deloitte',
    year: 2024,
    abstract: 'Annual technology trends report covering AI, cloud, cybersecurity, and emerging technologies transforming business.',
    url: 'https://www2.deloitte.com/us/en/insights/focus/tech-trends.html',
    topics: ['tech trends', 'ai', 'cloud', 'digital transformation'],
  },
  {
    id: 'research-deloitte-human-capital-2024',
    title: 'Human Capital Trends',
    institution: 'Deloitte',
    year: 2024,
    abstract: 'Annual survey of HR and workforce trends. Focus on AI augmentation, skills-based organizations, and worker wellbeing.',
    url: 'https://www2.deloitte.com/us/en/insights/focus/human-capital-trends.html',
    topics: ['human capital', 'hr trends', 'workforce', 'skills'],
  },
  {
    id: 'research-deloitte-ai-governance-2024',
    title: 'Trustworthy AI',
    institution: 'Deloitte',
    year: 2024,
    abstract: 'Framework for responsible AI governance. Risk management, ethics, and compliance in AI deployment.',
    url: 'https://www2.deloitte.com/us/en/pages/deloitte-analytics/solutions/ethics-of-ai-framework.html',
    topics: ['ai governance', 'ethics', 'risk', 'compliance'],
  },
  {
    id: 'research-pwc-global-ai-2024',
    title: 'Global AI Study: Sizing the Prize',
    institution: 'PwC',
    year: 2024,
    abstract: 'Economic impact analysis projecting AI contribution to global GDP, sector-specific opportunities, and regional variations in AI readiness.',
    url: 'https://www.pwc.com/gx/en/issues/artificial-intelligence.html',
    topics: ['ai economics', 'gdp impact', 'productivity', 'regional analysis'],
  },
  {
    id: 'research-pwc-workforce-2024',
    title: 'Workforce of the Future',
    institution: 'PwC',
    year: 2024,
    abstract: 'Research on changing workforce dynamics. Employee preferences, skills evolution, and organizational responses.',
    url: 'https://www.pwc.com/gx/en/issues/workforce.html',
    topics: ['workforce', 'skills', 'employee preferences', 'future of work'],
  },
  {
    id: 'research-pwc-ceo-survey-2024',
    title: 'Annual Global CEO Survey',
    institution: 'PwC',
    year: 2024,
    abstract: 'Survey of CEO perspectives on AI, digital transformation, workforce challenges, and business outlook.',
    url: 'https://www.pwc.com/gx/en/issues/c-suite-insights/ceo-survey.html',
    topics: ['ceo survey', 'ai strategy', 'business outlook', 'transformation'],
  },
  {
    id: 'research-pwc-responsible-ai-2024',
    title: 'Responsible AI Toolkit',
    institution: 'PwC',
    year: 2024,
    abstract: 'Framework and tools for implementing responsible AI practices in organizations.',
    url: 'https://www.pwc.com/gx/en/issues/data-and-analytics/artificial-intelligence/what-is-responsible-ai.html',
    topics: ['responsible ai', 'ethics', 'governance', 'implementation'],
  },
  {
    id: 'research-ey-ai-survey-2024',
    title: 'AI Survey',
    institution: 'EY',
    year: 2024,
    abstract: 'Global survey on AI adoption, investment priorities, and organizational readiness across industries.',
    url: 'https://www.ey.com/en_gl/ai',
    topics: ['ai adoption', 'investment', 'readiness', 'survey'],
  },
  {
    id: 'research-ey-future-work-2024',
    title: 'Work Reimagined',
    institution: 'EY',
    year: 2024,
    abstract: 'Research on evolving employee expectations, hybrid work models, and AI impact on workplace dynamics.',
    url: 'https://www.ey.com/en_gl/workforce/work-reimagined',
    topics: ['future of work', 'hybrid work', 'employee expectations', 'ai impact'],
  },
  {
    id: 'research-kpmg-ai-adoption-2024',
    title: 'AI Adoption Survey',
    institution: 'KPMG',
    year: 2024,
    abstract: 'Survey on enterprise AI adoption trends, challenges, and success factors across industries.',
    url: 'https://kpmg.com/xx/en/home/insights/2024/artificial-intelligence.html',
    topics: ['ai adoption', 'enterprise', 'challenges', 'success factors'],
  },
  {
    id: 'research-kpmg-future-work-2024',
    title: 'Future of Work',
    institution: 'KPMG',
    year: 2024,
    abstract: 'KPMG research on workforce transformation, automation impact, and organizational adaptation strategies.',
    url: 'https://kpmg.com/xx/en/home/insights/future-of-work.html',
    topics: ['future of work', 'automation', 'workforce', 'transformation'],
  },
  {
    id: 'research-accenture-tech-vision-2024',
    title: 'Technology Vision 2024',
    institution: 'Accenture',
    year: 2024,
    abstract: 'Annual technology trends report. Human-AI collaboration, responsible AI, and digital transformation strategies.',
    url: 'https://www.accenture.com/us-en/insights/technology/technology-trends',
    topics: ['tech vision', 'ai', 'digital transformation', 'human-ai collaboration'],
  },
  {
    id: 'research-accenture-future-workforce-2024',
    title: 'Future Workforce',
    institution: 'Accenture',
    year: 2024,
    abstract: 'Research on skills development, workforce planning, and AI-enabled talent management.',
    url: 'https://www.accenture.com/us-en/insights/future-workforce-index',
    topics: ['workforce', 'skills', 'talent management', 'ai'],
  },
  {
    id: 'research-accenture-genai-2024',
    title: 'Generative AI: A New Era of Enterprise Intelligence',
    institution: 'Accenture',
    year: 2024,
    abstract: 'Research on generative AI adoption in enterprises, use cases, and value creation strategies.',
    url: 'https://www.accenture.com/us-en/insights/generative-ai',
    topics: ['generative ai', 'enterprise', 'use cases', 'value creation'],
  },
  {
    id: 'research-capgemini-ai-2024',
    title: 'AI in Business',
    institution: 'Capgemini',
    year: 2024,
    abstract: 'Research on AI implementation success factors, organizational challenges, and business outcomes.',
    url: 'https://www.capgemini.com/insights/research-library/artificial-intelligence/',
    topics: ['ai', 'business', 'implementation', 'outcomes'],
  },
  {
    id: 'research-capgemini-world-report-2024',
    title: 'World Report Series',
    institution: 'Capgemini Research Institute',
    year: 2024,
    abstract: 'Annual research on digital transformation, AI adoption, and technology trends across industries.',
    url: 'https://www.capgemini.com/insights/research-institute/',
    topics: ['digital transformation', 'ai adoption', 'technology trends', 'research'],
  },
  {
    id: 'research-gartner-ai-hype-2023',
    title: 'Gartner Hype Cycle for Artificial Intelligence',
    institution: 'Gartner',
    year: 2023,
    abstract: 'Technology maturity assessment tracking generative AI, foundation models, and emerging AI technologies through the hype cycle phases.',
    url: 'https://www.gartner.com/en/articles/what-s-new-in-artificial-intelligence-from-the-2023-gartner-hype-cycle',
    topics: ['ai maturity', 'technology trends', 'hype cycle', 'generative ai'],
  },
  {
    id: 'research-gartner-top-tech-2024',
    title: 'Top Strategic Technology Trends',
    institution: 'Gartner',
    year: 2024,
    abstract: 'Annual forecast of strategic technology trends shaping business and IT. AI-centric predictions.',
    url: 'https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2024',
    topics: ['technology trends', 'ai', 'strategy', 'forecast'],
  },
  {
    id: 'research-bain-automation-2024',
    title: 'Automation and AI',
    institution: 'Bain & Company',
    year: 2024,
    abstract: 'Research on automation strategies, AI implementation, and workforce implications.',
    url: 'https://www.bain.com/insights/topics/artificial-intelligence/',
    topics: ['automation', 'ai', 'implementation', 'workforce'],
  },
  {
    id: 'research-bain-future-work-2024',
    title: 'The Working Future',
    institution: 'Bain & Company',
    year: 2024,
    abstract: 'Analysis of future work trends, talent strategies, and organizational transformation.',
    url: 'https://www.bain.com/insights/topics/future-of-work/',
    topics: ['future of work', 'talent', 'organization', 'transformation'],
  },
  {
    id: 'research-roland-berger-ai-2024',
    title: 'AI for Business',
    institution: 'Roland Berger',
    year: 2024,
    abstract: 'European perspective on AI in business, industry 4.0, and digital transformation strategies.',
    url: 'https://www.rolandberger.com/en/Insights/Artificial-Intelligence.html',
    topics: ['ai business', 'industry 4.0', 'digital transformation', 'europe'],
  },
  {
    id: 'research-oliver-wyman-ai-2024',
    title: 'The AI Imperative',
    institution: 'Oliver Wyman',
    year: 2024,
    abstract: 'Analysis of AI strategies for financial services and other industries.',
    url: 'https://www.oliverwyman.com/our-expertise/insights/artificial-intelligence.html',
    topics: ['ai strategy', 'financial services', 'transformation', 'implementation'],
  },

  // ===========================================================================
  // 4. TECH COMPANIES - 32 sources
  // ===========================================================================
  {
    id: 'research-google-ai-2024',
    title: 'Google AI Research',
    institution: 'Google',
    year: 2024,
    abstract: 'Google AI research publications covering machine learning, NLP, computer vision, and responsible AI development.',
    url: 'https://ai.google/research/',
    topics: ['ai research', 'machine learning', 'nlp', 'computer vision'],
  },
  {
    id: 'research-google-responsible-ai-2024',
    title: 'Responsible AI Practices',
    institution: 'Google',
    year: 2024,
    abstract: 'Google framework for developing and deploying AI responsibly. Fairness, interpretability, and safety guidelines.',
    url: 'https://ai.google/responsibility/responsible-ai-practices/',
    topics: ['responsible ai', 'fairness', 'safety', 'ethics'],
  },
  {
    id: 'research-microsoft-worklab-2024',
    title: 'Work Trend Index',
    institution: 'Microsoft',
    year: 2024,
    abstract: 'Annual survey on work patterns, productivity tools, and AI adoption in the workplace.',
    url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/',
    topics: ['work trends', 'productivity', 'ai adoption', 'workplace'],
  },
  {
    id: 'research-microsoft-ai-research-2024',
    title: 'Microsoft Research - AI',
    institution: 'Microsoft Research',
    year: 2024,
    abstract: 'Microsoft AI research covering foundation models, human-AI interaction, and responsible AI development.',
    url: 'https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/',
    topics: ['ai research', 'foundation models', 'human-ai interaction', 'responsible ai'],
  },
  {
    id: 'research-microsoft-responsible-ai-2024',
    title: 'Responsible AI Standard',
    institution: 'Microsoft',
    year: 2024,
    abstract: 'Microsoft framework and standards for responsible AI development and deployment.',
    url: 'https://www.microsoft.com/en-us/ai/responsible-ai',
    topics: ['responsible ai', 'standards', 'governance', 'deployment'],
  },
  {
    id: 'research-ibm-institute-2024',
    title: 'IBM Institute for Business Value',
    institution: 'IBM',
    year: 2024,
    abstract: 'Research on AI adoption, digital transformation, and technology strategy for enterprises.',
    url: 'https://www.ibm.com/thought-leadership/institute-business-value/',
    topics: ['ai adoption', 'digital transformation', 'strategy', 'enterprise'],
  },
  {
    id: 'research-ibm-ai-ethics-2024',
    title: 'IBM AI Ethics',
    institution: 'IBM',
    year: 2024,
    abstract: 'IBM framework for trustworthy AI including fairness, explainability, and robustness.',
    url: 'https://www.ibm.com/artificial-intelligence/ethics',
    topics: ['ai ethics', 'trustworthy ai', 'fairness', 'explainability'],
  },
  {
    id: 'research-salesforce-research-2024',
    title: 'Salesforce AI Research',
    institution: 'Salesforce',
    year: 2024,
    abstract: 'Research on AI for CRM, customer service automation, and enterprise AI applications.',
    url: 'https://www.salesforce.com/company/news-press/stories/ai-research/',
    topics: ['ai research', 'crm', 'automation', 'enterprise ai'],
  },
  {
    id: 'research-salesforce-state-ai-2024',
    title: 'State of AI Report',
    institution: 'Salesforce',
    year: 2024,
    abstract: 'Survey on AI adoption trends in sales, marketing, and customer service organizations.',
    url: 'https://www.salesforce.com/resources/research-reports/',
    topics: ['ai adoption', 'sales', 'marketing', 'customer service'],
  },
  {
    id: 'research-linkedin-economic-2024',
    title: 'Economic Graph',
    institution: 'LinkedIn',
    year: 2024,
    abstract: 'LinkedIn data insights on labor market trends, skills demand, and hiring patterns globally.',
    url: 'https://economicgraph.linkedin.com/',
    topics: ['labor market', 'skills', 'hiring', 'trends'],
  },
  {
    id: 'research-linkedin-future-work-2024',
    title: 'Future of Work Report',
    institution: 'LinkedIn',
    year: 2024,
    abstract: 'Analysis of changing work patterns, in-demand skills, and AI impact on professional roles.',
    url: 'https://www.linkedin.com/business/talent/blog/talent-strategy/future-of-work',
    topics: ['future of work', 'skills', 'ai impact', 'professional roles'],
  },
  {
    id: 'research-linkedin-jobs-rise-2024',
    title: 'Jobs on the Rise',
    institution: 'LinkedIn',
    year: 2024,
    abstract: 'Annual report on fastest-growing jobs and skills across industries and regions.',
    url: 'https://www.linkedin.com/pulse/linkedin-jobs-rise-2024/',
    topics: ['job growth', 'skills demand', 'career trends', 'hiring'],
  },
  {
    id: 'research-indeed-hiring-2024',
    title: 'Indeed Hiring Lab',
    institution: 'Indeed',
    year: 2024,
    abstract: 'Research on hiring trends, job market dynamics, and labor market conditions using job posting data.',
    url: 'https://www.hiringlab.org/',
    topics: ['hiring trends', 'job market', 'labor market', 'job postings'],
  },
  {
    id: 'research-glassdoor-economic-2024',
    title: 'Glassdoor Economic Research',
    institution: 'Glassdoor',
    year: 2024,
    abstract: 'Research on workplace trends, compensation, and employee sentiment using review and salary data.',
    url: 'https://www.glassdoor.com/research/',
    topics: ['workplace trends', 'compensation', 'employee sentiment', 'job market'],
  },
  {
    id: 'research-meta-ai-research-2024',
    title: 'Meta AI Research',
    institution: 'Meta',
    year: 2024,
    abstract: 'Meta AI research on machine learning, computer vision, NLP, and open-source AI models.',
    url: 'https://ai.meta.com/research/',
    topics: ['ai research', 'machine learning', 'open source', 'llm'],
  },
  {
    id: 'research-amazon-science-2024',
    title: 'Amazon Science',
    institution: 'Amazon',
    year: 2024,
    abstract: 'Amazon research on AI, machine learning, robotics, and automation in retail and logistics.',
    url: 'https://www.amazon.science/',
    topics: ['ai research', 'machine learning', 'robotics', 'automation'],
  },
  {
    id: 'research-nvidia-ai-2024',
    title: 'NVIDIA AI Research',
    institution: 'NVIDIA',
    year: 2024,
    abstract: 'Research on GPU computing, deep learning, and AI infrastructure for enterprise and research.',
    url: 'https://www.nvidia.com/en-us/research/',
    topics: ['gpu computing', 'deep learning', 'ai infrastructure', 'research'],
  },
  {
    id: 'research-intel-ai-2024',
    title: 'Intel AI',
    institution: 'Intel',
    year: 2024,
    abstract: 'Intel research on AI hardware, edge AI, and enterprise AI deployment.',
    url: 'https://www.intel.com/content/www/us/en/artificial-intelligence/overview.html',
    topics: ['ai hardware', 'edge ai', 'enterprise ai', 'deployment'],
  },
  {
    id: 'research-sap-insights-2024',
    title: 'SAP Insights',
    institution: 'SAP',
    year: 2024,
    abstract: 'Research on enterprise AI, ERP systems, and digital transformation in business.',
    url: 'https://www.sap.com/insights.html',
    topics: ['enterprise ai', 'erp', 'digital transformation', 'business'],
  },
  {
    id: 'research-oracle-ai-2024',
    title: 'Oracle AI',
    institution: 'Oracle',
    year: 2024,
    abstract: 'Research on AI in databases, cloud computing, and enterprise applications.',
    url: 'https://www.oracle.com/artificial-intelligence/',
    topics: ['ai databases', 'cloud computing', 'enterprise applications', 'automation'],
  },
  {
    id: 'research-openai-research-2024',
    title: 'OpenAI Research',
    institution: 'OpenAI',
    year: 2024,
    abstract: 'Research on large language models, safety, and AI capabilities from OpenAI.',
    url: 'https://openai.com/research/',
    topics: ['llm', 'ai safety', 'capabilities', 'research'],
  },
  {
    id: 'research-openai-economic-2024',
    title: 'GPTs are GPTs: Economic Impacts of AI',
    institution: 'OpenAI',
    year: 2024,
    abstract: 'Research on labor market exposure to GPT capabilities and economic implications.',
    url: 'https://openai.com/research/gpts-are-gpts',
    topics: ['economic impact', 'labor market', 'gpt', 'automation'],
  },
  {
    id: 'research-anthropic-research-2024',
    title: 'Anthropic Research',
    institution: 'Anthropic',
    year: 2024,
    abstract: 'AI safety research including constitutional AI, interpretability, and alignment.',
    url: 'https://www.anthropic.com/research',
    topics: ['ai safety', 'alignment', 'interpretability', 'research'],
  },
  {
    id: 'research-anthropic-claude-2024',
    title: 'Claude Model Card',
    institution: 'Anthropic',
    year: 2024,
    abstract: 'Technical documentation and research on Claude AI assistant capabilities and safety.',
    url: 'https://www.anthropic.com/claude',
    topics: ['llm', 'ai assistant', 'safety', 'capabilities'],
  },
  {
    id: 'research-deepmind-research-2024',
    title: 'DeepMind Research',
    institution: 'DeepMind',
    year: 2024,
    abstract: 'AI research covering reinforcement learning, protein folding, and general intelligence.',
    url: 'https://deepmind.google/research/',
    topics: ['ai research', 'reinforcement learning', 'agi', 'science'],
  },
  {
    id: 'research-deepmind-safety-2024',
    title: 'DeepMind Safety Research',
    institution: 'DeepMind',
    year: 2024,
    abstract: 'Research on AI safety, alignment, and responsible development of advanced AI.',
    url: 'https://deepmind.google/safety-research/',
    topics: ['ai safety', 'alignment', 'responsible ai', 'research'],
  },
  {
    id: 'research-huggingface-blog-2024',
    title: 'Hugging Face Blog',
    institution: 'Hugging Face',
    year: 2024,
    abstract: 'Research and developments in open-source AI, transformers, and ML democratization.',
    url: 'https://huggingface.co/blog',
    topics: ['open source ai', 'transformers', 'democratization', 'ml'],
  },
  {
    id: 'research-huggingface-leaderboard-2024',
    title: 'Open LLM Leaderboard',
    institution: 'Hugging Face',
    year: 2024,
    abstract: 'Benchmark tracking of open-source language model capabilities and performance.',
    url: 'https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard',
    topics: ['llm', 'benchmarks', 'open source', 'performance'],
  },
  {
    id: 'research-paperswithcode-2024',
    title: 'Papers With Code',
    institution: 'Papers With Code',
    year: 2024,
    abstract: 'Repository linking AI research papers with implementations and benchmarks.',
    url: 'https://paperswithcode.com/',
    topics: ['ai research', 'benchmarks', 'implementations', 'papers'],
  },
  {
    id: 'research-epoch-ai-2024',
    title: 'Epoch AI',
    institution: 'Epoch',
    year: 2024,
    abstract: 'Research on AI compute trends, model scaling, and AI development trajectories.',
    url: 'https://epochai.org/',
    topics: ['ai compute', 'scaling', 'trends', 'research'],
  },
  {
    id: 'research-redwood-research-2024',
    title: 'Redwood Research',
    institution: 'Redwood Research',
    year: 2024,
    abstract: 'Applied AI safety research including interpretability and adversarial robustness.',
    url: 'https://www.redwoodresearch.org/',
    topics: ['ai safety', 'interpretability', 'robustness', 'research'],
  },
  {
    id: 'research-conjecture-2024',
    title: 'Conjecture AI Safety',
    institution: 'Conjecture',
    year: 2024,
    abstract: 'AI safety company research on alignment and controllable AI systems.',
    url: 'https://www.conjecture.dev/',
    topics: ['ai safety', 'alignment', 'controllability', 'research'],
  },

  // ===========================================================================
  // 5. ACADEMIC/RESEARCH - 27 sources
  // ===========================================================================
  {
    id: 'research-stanford-hai-2024',
    title: 'AI Index Report 2024',
    institution: 'Stanford HAI',
    year: 2024,
    abstract: 'Annual comprehensive report tracking AI progress across research, industry, policy and public perception.',
    url: 'https://aiindex.stanford.edu/report/',
    topics: ['ai research', 'ai policy', 'ai investment', 'ai capabilities'],
  },
  {
    id: 'research-stanford-hai-genai-2024',
    title: 'Generative AI and the Labor Market',
    institution: 'Stanford HAI',
    year: 2024,
    abstract: 'Research on how generative AI affects workers, jobs, and skills across industries.',
    url: 'https://hai.stanford.edu/research/generative-ai',
    topics: ['generative ai', 'labor market', 'workers', 'skills'],
  },
  {
    id: 'research-stanford-hai-policy-2024',
    title: 'AI Policy and Governance',
    institution: 'Stanford HAI',
    year: 2024,
    abstract: 'Research on AI regulation, governance frameworks, and policy recommendations.',
    url: 'https://hai.stanford.edu/policy',
    topics: ['ai policy', 'governance', 'regulation', 'recommendations'],
  },
  {
    id: 'research-mit-sloan-ai-2024',
    title: 'MIT Sloan AI Research',
    institution: 'MIT Sloan School of Management',
    year: 2024,
    abstract: 'Research on AI strategy, digital transformation, and organizational adaptation to AI.',
    url: 'https://mitsloan.mit.edu/ideas-made-to-matter/topic/artificial-intelligence',
    topics: ['ai strategy', 'digital transformation', 'organization', 'management'],
  },
  {
    id: 'research-mit-work-future-2024',
    title: 'MIT Work of the Future',
    institution: 'MIT',
    year: 2024,
    abstract: 'Task Force on the Work of the Future examining technology impact on work and workers.',
    url: 'https://workofthefuture.mit.edu/',
    topics: ['future of work', 'technology', 'workers', 'policy'],
  },
  {
    id: 'research-mit-csail-ai-2024',
    title: 'MIT CSAIL AI Research',
    institution: 'MIT CSAIL',
    year: 2024,
    abstract: 'Computer Science and AI Laboratory research on machine learning, robotics, and AI systems.',
    url: 'https://www.csail.mit.edu/research/artificial-intelligence',
    topics: ['ai research', 'machine learning', 'robotics', 'ai systems'],
  },
  {
    id: 'research-oxford-future-humanity-2024',
    title: 'Future of Humanity Institute',
    institution: 'Oxford University',
    year: 2024,
    abstract: 'Research on existential risks, AI safety, and long-term impacts of advanced AI.',
    url: 'https://www.fhi.ox.ac.uk/',
    topics: ['ai safety', 'existential risk', 'long-term ai', 'governance'],
  },
  {
    id: 'research-oxford-martin-2024',
    title: 'Oxford Martin School',
    institution: 'Oxford University',
    year: 2024,
    abstract: 'Research on technological change, employment, and future of work challenges.',
    url: 'https://www.oxfordmartin.ox.ac.uk/',
    topics: ['technological change', 'employment', 'future of work', 'research'],
  },
  {
    id: 'research-oxford-automation-2024',
    title: 'The Future of Employment',
    institution: 'Oxford University',
    year: 2024,
    abstract: 'Frey and Osborne research on job automation susceptibility and labor market impacts.',
    url: 'https://www.oxfordmartin.ox.ac.uk/publications/the-future-of-employment/',
    topics: ['automation', 'employment', 'job risk', 'labor market'],
  },
  {
    id: 'research-cambridge-ai-2024',
    title: 'Cambridge Centre for AI in Medicine',
    institution: 'Cambridge University',
    year: 2024,
    abstract: 'Research on AI applications in healthcare, medical diagnostics, and drug discovery.',
    url: 'https://www.cam.ac.uk/research/research-at-cambridge/artificial-intelligence',
    topics: ['ai healthcare', 'medical ai', 'diagnostics', 'drug discovery'],
  },
  {
    id: 'research-hbs-ai-2024',
    title: 'Harvard Business Review - AI',
    institution: 'Harvard Business School',
    year: 2024,
    abstract: 'Business research and analysis on AI strategy, implementation, and organizational impact.',
    url: 'https://hbr.org/topic/subject/ai-and-machine-learning',
    topics: ['ai strategy', 'implementation', 'organization', 'business'],
  },
  {
    id: 'research-berkeley-ai-2024',
    title: 'Berkeley AI Research',
    institution: 'UC Berkeley',
    year: 2024,
    abstract: 'BAIR research on machine learning, robotics, computer vision, and NLP.',
    url: 'https://bair.berkeley.edu/',
    topics: ['ai research', 'machine learning', 'robotics', 'nlp'],
  },
  {
    id: 'research-cmu-ai-2024',
    title: 'CMU AI Research',
    institution: 'Carnegie Mellon University',
    year: 2024,
    abstract: 'Research on machine learning, robotics, and AI systems from Carnegie Mellon.',
    url: 'https://www.cmu.edu/ai/',
    topics: ['ai research', 'machine learning', 'robotics', 'ai systems'],
  },
  {
    id: 'research-eth-ai-center-2024',
    title: 'ETH AI Center',
    institution: 'ETH Zürich',
    year: 2024,
    abstract: 'Swiss research center for AI covering machine learning, robotics, and AI applications.',
    url: 'https://ai.ethz.ch/',
    topics: ['ai research', 'machine learning', 'robotics', 'switzerland'],
  },
  {
    id: 'research-eth-digital-2024',
    title: 'ETH Digital Transformation',
    institution: 'ETH Zürich',
    year: 2024,
    abstract: 'Research on digital transformation, Industry 4.0, and technology-driven change.',
    url: 'https://ethz.ch/en/industry/industry-4-0.html',
    topics: ['digital transformation', 'industry 4.0', 'technology', 'research'],
  },
  {
    id: 'research-kof-forecast-2024',
    title: 'KOF Konjunkturprognose',
    institution: 'KOF ETH Zürich',
    year: 2024,
    abstract: 'Quarterly economic forecasts from ETH Zürich covering GDP growth, employment trends.',
    url: 'https://kof.ethz.ch/en/forecasts-and-indicators.html',
    topics: ['konjunktur', 'prognose', 'beschäftigung', 'wirtschaftswachstum'],
  },
  {
    id: 'research-kof-digitalbarometer-2024',
    title: 'KOF Digitalbarometer',
    institution: 'KOF ETH Zürich',
    year: 2024,
    abstract: 'Messung der Digitalisierung in Schweizer Unternehmen. Technologieadoption und Arbeitswelt.',
    url: 'https://kof.ethz.ch/en/forecasts-and-indicators/indicators/kof-digitalisation-barometer.html',
    topics: ['digitalisierung', 'unternehmen', 'technologie', 'arbeitswelt'],
  },
  {
    id: 'research-bak-economics-2024',
    title: 'BAK Economics Prognosen',
    institution: 'BAK Economics',
    year: 2024,
    abstract: 'Wirtschaftsprognosen und Branchenanalysen für die Schweiz von BAK Economics.',
    url: 'https://www.bak-economics.com/',
    topics: ['wirtschaft', 'prognose', 'branchen', 'regional'],
  },
  {
    id: 'research-epfl-ai-2024',
    title: 'EPFL AI Research',
    institution: 'EPFL',
    year: 2024,
    abstract: 'Swiss research on machine learning, data science, and AI applications.',
    url: 'https://www.epfl.ch/research/domains/artificial-intelligence/',
    topics: ['ai research', 'machine learning', 'data science', 'switzerland'],
  },
  {
    id: 'research-uzh-digital-2024',
    title: 'UZH Digital Society Initiative',
    institution: 'Universität Zürich',
    year: 2024,
    abstract: 'Research on digital society, AI ethics, and technology impact on society.',
    url: 'https://www.dsi.uzh.ch/',
    topics: ['digital society', 'ai ethics', 'technology impact', 'research'],
  },
  {
    id: 'research-unisg-ai-2024',
    title: 'HSG AI and Business',
    institution: 'Universität St. Gallen',
    year: 2024,
    abstract: 'Research on AI in business, management, and organizational transformation.',
    url: 'https://ics.unisg.ch/',
    topics: ['ai business', 'management', 'organization', 'transformation'],
  },
  {
    id: 'research-zhaw-digitalisation-2024',
    title: 'ZHAW Digitalisierung',
    institution: 'ZHAW',
    year: 2024,
    abstract: 'Applied research on digitalization, AI applications, and workforce development.',
    url: 'https://www.zhaw.ch/de/forschung/forschungsschwerpunkte/digitalisierung/',
    topics: ['digitalization', 'ai applications', 'workforce', 'applied research'],
  },
  {
    id: 'research-fhnw-ai-2024',
    title: 'FHNW AI Research',
    institution: 'FHNW',
    year: 2024,
    abstract: 'Applied university research on AI, data science, and digital transformation.',
    url: 'https://www.fhnw.ch/de/forschung-und-dienstleistungen/technik/digital-technologies',
    topics: ['ai research', 'data science', 'digital transformation', 'applied research'],
  },
  {
    id: 'research-idiap-2024',
    title: 'Idiap Research Institute',
    institution: 'Idiap',
    year: 2024,
    abstract: 'Swiss research institute for AI, machine learning, and human-machine interaction.',
    url: 'https://www.idiap.ch/',
    topics: ['ai research', 'machine learning', 'human-machine interaction', 'switzerland'],
  },
  {
    id: 'research-nber-ai-2024',
    title: 'NBER AI Economics',
    institution: 'NBER',
    year: 2024,
    abstract: 'Economic research on AI impact on productivity, wages, and employment.',
    url: 'https://www.nber.org/topics/artificial-intelligence',
    topics: ['ai economics', 'productivity', 'wages', 'employment'],
  },
  {
    id: 'research-arxiv-ai-2024',
    title: 'arXiv AI/ML Papers',
    institution: 'arXiv',
    year: 2024,
    abstract: 'Open access repository for AI and machine learning research papers.',
    url: 'https://arxiv.org/list/cs.AI/recent',
    topics: ['ai research', 'machine learning', 'papers', 'open access'],
  },
  {
    id: 'research-our-world-data-ai-2024',
    title: 'Our World in Data - AI',
    institution: 'Our World in Data',
    year: 2024,
    abstract: 'Data and visualizations on AI development, adoption, and societal impacts.',
    url: 'https://ourworldindata.org/artificial-intelligence',
    topics: ['ai data', 'visualizations', 'trends', 'society'],
  },

  // ===========================================================================
  // 6. THINK TANKS - 23 sources
  // ===========================================================================
  {
    id: 'research-avenir-suisse-digital-2024',
    title: 'Digitalisierung der Schweizer Wirtschaft',
    institution: 'Avenir Suisse',
    year: 2024,
    abstract: 'Think tank analysis of Swiss digitalization progress, regulatory environment, and competitiveness.',
    url: 'https://www.avenir-suisse.ch/themen/digitalisierung/',
    topics: ['digitalisierung', 'innovation', 'regulierung', 'wettbewerbsfähigkeit'],
  },
  {
    id: 'research-avenir-suisse-arbeitsmarkt-2024',
    title: 'Arbeitsmarkt Schweiz',
    institution: 'Avenir Suisse',
    year: 2024,
    abstract: 'Analysis of Swiss labor market challenges, structural changes, and policy recommendations.',
    url: 'https://www.avenir-suisse.ch/themen/arbeitsmarkt/',
    topics: ['arbeitsmarkt', 'strukturwandel', 'policy', 'schweiz'],
  },
  {
    id: 'research-avenir-suisse-bildung-2024',
    title: 'Bildung und Weiterbildung',
    institution: 'Avenir Suisse',
    year: 2024,
    abstract: 'Research on Swiss education system, lifelong learning, and skills development.',
    url: 'https://www.avenir-suisse.ch/themen/bildung/',
    topics: ['bildung', 'weiterbildung', 'skills', 'lifelong learning'],
  },
  {
    id: 'research-economiesuisse-digital-2024',
    title: 'Digitalisierung und Innovation',
    institution: 'economiesuisse',
    year: 2024,
    abstract: 'Swiss business federation analysis of digital transformation and innovation policy.',
    url: 'https://www.economiesuisse.ch/de/dossier-politik/digitalisierung',
    topics: ['digitalisierung', 'innovation', 'wirtschaftspolitik', 'schweiz'],
  },
  {
    id: 'research-economiesuisse-arbeitsmarkt-2024',
    title: 'Arbeitsmarktpolitik',
    institution: 'economiesuisse',
    year: 2024,
    abstract: 'Business perspective on Swiss labor market policy and workforce challenges.',
    url: 'https://www.economiesuisse.ch/de/dossier-politik/arbeitsmarkt',
    topics: ['arbeitsmarkt', 'wirtschaftspolitik', 'fachkräfte', 'schweiz'],
  },
  {
    id: 'research-brookings-ai-2024',
    title: 'Brookings AI Research',
    institution: 'Brookings Institution',
    year: 2024,
    abstract: 'Policy research on AI governance, workforce impacts, and economic implications.',
    url: 'https://www.brookings.edu/topic/artificial-intelligence/',
    topics: ['ai policy', 'governance', 'workforce', 'economics'],
  },
  {
    id: 'research-brookings-future-work-2024',
    title: 'Future of Work Initiative',
    institution: 'Brookings Institution',
    year: 2024,
    abstract: 'Research on automation, workforce development, and social protection policies.',
    url: 'https://www.brookings.edu/projects/workforce-of-the-future/',
    topics: ['future of work', 'automation', 'workforce development', 'policy'],
  },
  {
    id: 'research-rand-ai-2024',
    title: 'RAND AI Research',
    institution: 'RAND Corporation',
    year: 2024,
    abstract: 'Policy research on AI national security, workforce, and societal implications.',
    url: 'https://www.rand.org/topics/artificial-intelligence.html',
    topics: ['ai policy', 'national security', 'workforce', 'society'],
  },
  {
    id: 'research-bruegel-digital-2024',
    title: 'Bruegel Digital Economy',
    institution: 'Bruegel',
    year: 2024,
    abstract: 'European policy research on digital economy, AI regulation, and labor markets.',
    url: 'https://www.bruegel.org/topic/digital-economy',
    topics: ['digital economy', 'ai regulation', 'labor market', 'europe'],
  },
  {
    id: 'research-bruegel-ai-2024',
    title: 'Bruegel AI Policy',
    institution: 'Bruegel',
    year: 2024,
    abstract: 'Research on European AI strategy, innovation policy, and competitiveness.',
    url: 'https://www.bruegel.org/topic/artificial-intelligence',
    topics: ['ai policy', 'innovation', 'competitiveness', 'europe'],
  },
  {
    id: 'research-ai-now-2024',
    title: 'AI Now Institute',
    institution: 'AI Now Institute',
    year: 2024,
    abstract: 'Research on social implications of AI including bias, labor impacts, and governance.',
    url: 'https://ainowinstitute.org/',
    topics: ['ai social impact', 'bias', 'labor', 'governance'],
  },
  {
    id: 'research-cais-safety-2024',
    title: 'Center for AI Safety',
    institution: 'Center for AI Safety',
    year: 2024,
    abstract: 'Research on AI safety, alignment, and reducing risks from advanced AI systems.',
    url: 'https://www.safe.ai/',
    topics: ['ai safety', 'alignment', 'risk reduction', 'advanced ai'],
  },
  {
    id: 'research-cset-ai-2024',
    title: 'CSET AI Research',
    institution: 'Georgetown CSET',
    year: 2024,
    abstract: 'Research on AI and emerging technologies for security policy.',
    url: 'https://cset.georgetown.edu/',
    topics: ['ai', 'security policy', 'emerging tech', 'research'],
  },
  {
    id: 'research-aspen-ai-2024',
    title: 'Aspen Digital',
    institution: 'Aspen Institute',
    year: 2024,
    abstract: 'Policy discussions on AI, digital economy, and technology governance.',
    url: 'https://www.aspeninstitute.org/programs/aspen-digital/',
    topics: ['ai policy', 'digital economy', 'governance', 'discussion'],
  },
  {
    id: 'research-ceps-ai-2024',
    title: 'CEPS Digital Policy',
    institution: 'Centre for European Policy Studies',
    year: 2024,
    abstract: 'European think tank research on digital policy, AI regulation, and data governance.',
    url: 'https://www.ceps.eu/topics/digital-economy/',
    topics: ['digital policy', 'ai regulation', 'data governance', 'europe'],
  },
  {
    id: 'research-ifo-digital-2024',
    title: 'ifo Digitalisierung',
    institution: 'ifo Institut',
    year: 2024,
    abstract: 'German economic research on digitalization, AI adoption, and labor market effects.',
    url: 'https://www.ifo.de/forschung/digitalisierung',
    topics: ['digitalization', 'ai adoption', 'labor market', 'germany'],
  },
  {
    id: 'research-iab-arbeitsmarkt-2024',
    title: 'IAB Arbeitsmarktforschung',
    institution: 'IAB',
    year: 2024,
    abstract: 'German labor market research including automation and AI impact studies.',
    url: 'https://www.iab.de/',
    topics: ['labor market', 'automation', 'employment', 'germany'],
  },
  {
    id: 'research-nesta-ai-2024',
    title: 'Nesta AI',
    institution: 'Nesta',
    year: 2024,
    abstract: 'UK innovation foundation research on AI, skills, and future of work.',
    url: 'https://www.nesta.org.uk/project/future-skills/',
    topics: ['ai', 'skills', 'innovation', 'future of work'],
  },
  {
    id: 'research-ai-impacts-2024',
    title: 'AI Impacts',
    institution: 'AI Impacts',
    year: 2024,
    abstract: 'Research on AI timelines, capabilities, and societal implications.',
    url: 'https://aiimpacts.org/',
    topics: ['ai timelines', 'capabilities', 'implications', 'research'],
  },
  {
    id: 'research-alignment-forum-2024',
    title: 'AI Alignment Forum',
    institution: 'Alignment Forum',
    year: 2024,
    abstract: 'Community research on AI alignment, safety, and governance challenges.',
    url: 'https://www.alignmentforum.org/',
    topics: ['ai alignment', 'safety', 'governance', 'research'],
  },
  {
    id: 'research-lesswrong-ai-2024',
    title: 'LessWrong AI',
    institution: 'LessWrong',
    year: 2024,
    abstract: 'Community discussions and research on AI safety and rationality.',
    url: 'https://www.lesswrong.com/tag/ai',
    topics: ['ai safety', 'rationality', 'community', 'research'],
  },
  {
    id: 'research-80000hours-ai-2024',
    title: '80,000 Hours - AI Safety',
    institution: '80,000 Hours',
    year: 2024,
    abstract: 'Career guidance and research on AI safety as a global priority.',
    url: 'https://80000hours.org/problem-profiles/artificial-intelligence/',
    topics: ['ai safety', 'careers', 'global priorities', 'research'],
  },
  {
    id: 'research-miri-2024',
    title: 'MIRI Research',
    institution: 'Machine Intelligence Research Institute',
    year: 2024,
    abstract: 'Technical AI alignment research focused on mathematical foundations of safety.',
    url: 'https://intelligence.org/research/',
    topics: ['ai alignment', 'safety', 'mathematics', 'research'],
  },

  // ===========================================================================
  // 7. FINANCE SECTOR - 12 sources
  // ===========================================================================
  {
    id: 'research-ubs-research-2024',
    title: 'UBS Global Research',
    institution: 'UBS',
    year: 2024,
    abstract: 'UBS research on global economic trends, technology disruption, and investment implications.',
    url: 'https://www.ubs.com/global/en/wealth-management/insights.html',
    topics: ['global economy', 'technology', 'investment', 'trends'],
  },
  {
    id: 'research-ubs-ai-2024',
    title: 'UBS AI in Finance',
    institution: 'UBS',
    year: 2024,
    abstract: 'Research on AI adoption in financial services, wealth management, and banking.',
    url: 'https://www.ubs.com/global/en/wealth-management/chief-investment-office/life-goals/technology.html',
    topics: ['ai finance', 'wealth management', 'banking', 'technology'],
  },
  {
    id: 'research-ubs-switzerland-2024',
    title: 'UBS Switzerland Economic Analysis',
    institution: 'UBS',
    year: 2024,
    abstract: 'Economic analysis focused on Swiss economy, real estate, and regional development.',
    url: 'https://www.ubs.com/ch/de/wealth-management/insights.html',
    topics: ['swiss economy', 'real estate', 'regional', 'analysis'],
  },
  {
    id: 'research-swiss-re-sigma-2024',
    title: 'Swiss Re Sigma',
    institution: 'Swiss Re',
    year: 2024,
    abstract: 'Insurance industry research including technology adoption, risk assessment, and market trends.',
    url: 'https://www.swissre.com/institute/research/sigma-research.html',
    topics: ['insurance', 'technology', 'risk', 'market trends'],
  },
  {
    id: 'research-swiss-re-ai-2024',
    title: 'Swiss Re AI and Insurance',
    institution: 'Swiss Re',
    year: 2024,
    abstract: 'Research on AI applications in insurance, underwriting automation, and claims processing.',
    url: 'https://www.swissre.com/institute/research/topics-and-risk-dialogues/digital-technology.html',
    topics: ['ai insurance', 'underwriting', 'automation', 'claims'],
  },
  {
    id: 'research-zurich-insurance-2024',
    title: 'Zurich Insurance Research',
    institution: 'Zurich Insurance',
    year: 2024,
    abstract: 'Insurance industry research on risk trends, technology, and workforce changes.',
    url: 'https://www.zurich.com/knowledge',
    topics: ['insurance', 'risk trends', 'technology', 'workforce'],
  },
  {
    id: 'research-raiffeisen-research-2024',
    title: 'Raiffeisen Economic Research',
    institution: 'Raiffeisen',
    year: 2024,
    abstract: 'Swiss regional bank economic research focusing on SMEs and regional development.',
    url: 'https://www.raiffeisen.ch/rch/de/ueber-uns/raiffeisen-gruppe/publikationen/economic-research.html',
    topics: ['swiss economy', 'sme', 'regional', 'banking'],
  },
  {
    id: 'research-zkb-research-2024',
    title: 'ZKB Research',
    institution: 'Zürcher Kantonalbank',
    year: 2024,
    abstract: 'Cantonal bank research on Swiss economy, sustainability, and investment trends.',
    url: 'https://www.zkb.ch/de/ueber-uns/medien/publikationen.html',
    topics: ['swiss economy', 'sustainability', 'investment', 'zurich'],
  },
  {
    id: 'research-sif-fintech-2024',
    title: 'Swiss Fintech Report',
    institution: 'SIF/SFTI',
    year: 2024,
    abstract: 'State Secretariat for International Finance analysis of Swiss fintech ecosystem.',
    url: 'https://www.sif.admin.ch/sif/en/home/finanzmarktpolitik/digit-finanzsektor.html',
    topics: ['fintech', 'financial innovation', 'regulation', 'switzerland'],
  },
  {
    id: 'research-sfti-innovation-2024',
    title: 'Swiss Finance + Technology Association',
    institution: 'SFTI',
    year: 2024,
    abstract: 'Industry association research on fintech innovation and digital finance in Switzerland.',
    url: 'https://swissfinte.ch/',
    topics: ['fintech', 'innovation', 'digital finance', 'switzerland'],
  },
  {
    id: 'research-sba-banking-2024',
    title: 'Swiss Bankers Association',
    institution: 'SBA',
    year: 2024,
    abstract: 'Banking industry analysis including digitalization, workforce, and regulatory trends.',
    url: 'https://www.swissbanking.ch/en/topics',
    topics: ['banking', 'digitalization', 'workforce', 'regulation'],
  },
  {
    id: 'research-finma-annual-2024',
    title: 'FINMA Annual Report',
    institution: 'FINMA',
    year: 2024,
    abstract: 'Swiss financial market supervisory authority report on regulation, fintech, and market developments.',
    url: 'https://www.finma.ch/en/documentation/finma-publications/annual-reports/',
    topics: ['regulation', 'fintech', 'supervision', 'financial market'],
  },

  // ===========================================================================
  // 8. INDUSTRY ASSOCIATIONS - 16 sources
  // ===========================================================================
  {
    id: 'research-swissmem-industrie-2024',
    title: 'Swissmem Industrie 4.0',
    institution: 'Swissmem',
    year: 2024,
    abstract: 'Swiss mechanical engineering association research on Industry 4.0 and manufacturing automation.',
    url: 'https://www.swissmem.ch/de/themen/industrie-40.html',
    topics: ['industry 4.0', 'manufacturing', 'automation', 'switzerland'],
  },
  {
    id: 'research-swissmem-arbeitsmarkt-2024',
    title: 'Swissmem Arbeitsmarkt',
    institution: 'Swissmem',
    year: 2024,
    abstract: 'MEM industry labor market analysis including skills demand and workforce development.',
    url: 'https://www.swissmem.ch/de/themen/arbeitswelt.html',
    topics: ['labor market', 'manufacturing', 'skills', 'workforce'],
  },
  {
    id: 'research-digitalswitzerland-2024',
    title: 'Digital Switzerland',
    institution: 'digitalswitzerland',
    year: 2024,
    abstract: 'Cross-sector initiative promoting digital transformation of Switzerland.',
    url: 'https://digitalswitzerland.com/',
    topics: ['digitalization', 'innovation', 'startup', 'switzerland'],
  },
  {
    id: 'research-swisscom-digital-2024',
    title: 'Digital Switzerland Report',
    institution: 'Swisscom',
    year: 2024,
    abstract: 'Jährlicher Bericht zur digitalen Transformation der Schweiz. ICT-Trends und Cybersecurity.',
    url: 'https://www.swisscom.ch/de/business/enterprise/themen/digital-business.html',
    topics: ['digitalisierung', 'ict', 'cybersecurity', 'digital business'],
  },
  {
    id: 'research-swiss-digital-initiative-2024',
    title: 'Swiss Digital Initiative',
    institution: 'Swiss Digital Initiative',
    year: 2024,
    abstract: 'Initiative für digitale Ethik und verantwortungsvolle Technologie. Digital Trust Label.',
    url: 'https://www.swiss-digital-initiative.org/',
    topics: ['digital ethics', 'ai guidelines', 'trust', 'verantwortung'],
  },
  {
    id: 'research-ict-switzerland-2024',
    title: 'ICT Switzerland',
    institution: 'ICT Switzerland',
    year: 2024,
    abstract: 'ICT industry association analysis of IT labor market and digital skills demand.',
    url: 'https://www.ict-switzerland.ch/',
    topics: ['ict', 'labor market', 'digital skills', 'switzerland'],
  },
  {
    id: 'research-swico-ict-2024',
    title: 'Swico ICT Report',
    institution: 'Swico',
    year: 2024,
    abstract: 'Swiss ICT industry report on market trends, employment, and technology adoption.',
    url: 'https://www.swico.ch/',
    topics: ['ict', 'market trends', 'employment', 'technology'],
  },
  {
    id: 'research-sgv-arbeitsmarkt-2024',
    title: 'Schweizerischer Gewerbeverband',
    institution: 'SGV',
    year: 2024,
    abstract: 'Swiss trade association perspective on SME labor market and digitalization.',
    url: 'https://www.sgv-usam.ch/',
    topics: ['sme', 'labor market', 'digitalization', 'gewerbe'],
  },
  {
    id: 'research-sav-arbeitgeber-2024',
    title: 'Schweizerischer Arbeitgeberverband',
    institution: 'SAV',
    year: 2024,
    abstract: 'Employer association analysis of labor market policy and workforce challenges.',
    url: 'https://www.arbeitgeber.ch/',
    topics: ['employer', 'labor policy', 'workforce', 'switzerland'],
  },
  {
    id: 'research-travail-suisse-2024',
    title: 'Travail.Suisse Digitalisierung',
    institution: 'Travail.Suisse',
    year: 2024,
    abstract: 'Worker organization perspective on digitalization and labor market transformation.',
    url: 'https://www.travailsuisse.ch/',
    topics: ['workers', 'digitalization', 'labor rights', 'transformation'],
  },
  {
    id: 'research-sgb-gewerkschaft-2024',
    title: 'SGB Digitalisierung',
    institution: 'Schweizerischer Gewerkschaftsbund',
    year: 2024,
    abstract: 'Swiss trade union federation analysis of digitalization impact on workers.',
    url: 'https://www.sgb.ch/',
    topics: ['union', 'digitalization', 'workers', 'labor rights'],
  },
  {
    id: 'research-scienceindustries-2024',
    title: 'scienceindustries',
    institution: 'scienceindustries',
    year: 2024,
    abstract: 'Swiss chemical and pharmaceutical industry association research on innovation.',
    url: 'https://www.scienceindustries.ch/',
    topics: ['pharma', 'chemical', 'innovation', 'workforce'],
  },
  {
    id: 'research-swiss-medtech-2024',
    title: 'Swiss Medtech',
    institution: 'Swiss Medtech',
    year: 2024,
    abstract: 'Medical technology industry analysis including AI applications and workforce needs.',
    url: 'https://www.swiss-medtech.ch/',
    topics: ['medtech', 'ai healthcare', 'innovation', 'workforce'],
  },
  {
    id: 'research-asut-telecom-2024',
    title: 'asut Telekommunikation',
    institution: 'asut',
    year: 2024,
    abstract: 'Swiss telecommunications association research on infrastructure and digital services.',
    url: 'https://asut.ch/',
    topics: ['telecom', 'infrastructure', 'digital services', 'connectivity'],
  },
  {
    id: 'research-gastrosuisse-2024',
    title: 'GastroSuisse Digitalisierung',
    institution: 'GastroSuisse',
    year: 2024,
    abstract: 'Hospitality industry perspective on digitalization and automation.',
    url: 'https://www.gastrosuisse.ch/',
    topics: ['hospitality', 'digitalization', 'automation', 'gastgewerbe'],
  },
  {
    id: 'research-hotelleriesuisse-2024',
    title: 'HotellerieSuisse',
    institution: 'HotellerieSuisse',
    year: 2024,
    abstract: 'Hotel industry analysis of technology adoption and workforce trends.',
    url: 'https://www.hotelleriesuisse.ch/',
    topics: ['hotel', 'technology', 'workforce', 'tourism'],
  },
];

// Export count by category for statistics
export const SOURCE_STATS = {
  total: RESEARCH_SOURCES.length,
  byCategory: {
    government: 15,
    international: 25,
    consulting: 31,
    tech: 32,
    academic: 27,
    'think-tank': 23,
    finance: 12,
    industry: 16,
  },
};
